db:
  image: postgres
  ports:
    - "5432"

redis:
  image: redis
  ports:
    - "6379"

sidekiq:
  build: .
  command: bundle exec sidekiq
  volumes:
    - .:/lens_server
  links:
    - db
    - redis

web:
  build: .
  command: bundle exec unicorn -p 3000
  volumes:
    - .:/lens_server
  ports:
    - "3000:3000"
  links:
    - db
    - redis
